(() => {
  'use strict';
  const KEY = 'tth-studio-v2';
  const PROJECTS = 'tth-projects-v2';
  const defaults = { paper:'ruled', pen:'blue', realism:35, rotation:2, opacity:92, spacing:0, lineHeight:32 };
  const papers = {
    ruled:{name:'Ruled Notebook', bg:'#fff', line:'#cbd5e1'},
    blank:{name:'Blank White', bg:'#fff', line:'transparent'},
    cream:{name:'Warm Cream', bg:'#fffaf0', line:'#d8d1bf'},
    exam:{name:'Exam Sheet', bg:'#fff', line:'#d7dee8'},
    vintage:{name:'Vintage Paper', bg:'#f7efd9', line:'#cbbd9b'}
  };
  const pens = { blue:{name:'Blue Pen',color:'#183b8c'}, black:{name:'Black Pen',color:'#171717'}, darkblue:{name:'Dark Blue',color:'#102a56'}, pencil:{name:'Pencil',color:'#4b5563'} };
  const state = Object.assign({}, defaults, JSON.parse(localStorage.getItem(KEY) || '{}'));
  let panel;
  const save = () => localStorage.setItem(KEY, JSON.stringify(state));
  const toast = m => { let t=document.getElementById('studio-toast'); if(!t){t=document.createElement('div');t.id='studio-toast';t.style.cssText='position:fixed;bottom:20px;left:50%;transform:translateX(-50%);z-index:10050;padding:10px 15px;border-radius:14px;background:#0f172a;color:#fff;font:600 13px system-ui;box-shadow:0 12px 30px #0002';document.body.appendChild(t)} t.textContent=m;t.hidden=false;clearTimeout(t.x);t.x=setTimeout(()=>t.hidden=true,2200)};
  const css = `.studio-v2{position:fixed;right:16px;bottom:78px;z-index:10020;width:min(360px,calc(100vw - 32px));max-height:min(78vh,680px);overflow:auto;background:rgba(255,255,255,.97);border:1px solid #e2e8f0;border-radius:20px;box-shadow:0 24px 70px #0f172a2b;padding:16px;font:14px system-ui;color:#0f172a}.studio-v2 h3{margin:0;font-size:17px}.studio-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.studio-grid button,.studio-actions button{border:1px solid #e2e8f0;background:#f8fafc;border-radius:12px;padding:9px;cursor:pointer;font-weight:650}.studio-grid button.active{border-color:#0284c7;background:#e0f2fe;color:#0369a1}.studio-row{margin-top:13px}.studio-row label{display:flex;justify-content:space-between;font-size:12px;font-weight:700;margin-bottom:5px}.studio-row input{width:100%}.studio-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:15px}.studio-actions .primary{background:#0284c7;color:white;border-color:#0284c7}.studio-close{position:absolute;right:12px;top:10px;border:0;background:transparent;font-size:20px;cursor:pointer}.studio-install{position:fixed;right:16px;bottom:78px;z-index:10019;border:0;border-radius:15px;padding:11px 14px;background:#0284c7;color:#fff;font:700 13px system-ui;box-shadow:0 10px 30px #0284c74d}.studio-saved{font-size:11px;color:#64748b;margin-top:8px}`;
  const inject=()=>{const s=document.createElement('style');s.textContent=css;document.head.appendChild(s)};
  const apply=()=>{
    const sheet=document.querySelector('.paper-sheet'); if(sheet){const p=papers[state.paper];sheet.style.backgroundColor=p.bg; sheet.style.setProperty('--studio-line',p.line)}
    const content=document.querySelector('.paper-content'); if(content){const p=pens[state.pen];content.style.color=p.color;content.style.lineHeight=state.lineHeight+'px';content.style.letterSpacing=state.spacing+'px';content.style.textShadow=`${state.rotation/10}px ${state.realism/30}px ${Math.max(0,state.realism/20)}px rgba(0,0,0,${Math.max(0,(100-state.opacity)/1000)})`}
    document.querySelectorAll('.paper-line-row').forEach(x=>x.style.borderBottomColor=papers[state.paper].line);
    save();
  };
  const render=()=>{if(panel)panel.remove();panel=document.createElement('aside');panel.className='studio-v2';panel.innerHTML=`<button class="studio-close" aria-label="Close">×</button><h3>Handwriting Studio</h3><div class="studio-saved">Settings are saved on this device.</div><div class="studio-row"><label>Paper</label><div class="studio-grid">${Object.entries(papers).map(([k,v])=>`<button data-paper="${k}" class="${state.paper===k?'active':''}">${v.name}</button>`).join('')}</div></div><div class="studio-row"><label>Pen <span>${pens[state.pen].name}</span></label><div class="studio-grid">${Object.entries(pens).map(([k,v])=>`<button data-pen="${k}" class="${state.pen===k?'active':''}">${v.name}</button>`).join('')}</div></div><div class="studio-row"><label>Realism <output>${state.realism}</output></label><input data-range="realism" type="range" min="0" max="100" value="${state.realism}"></div><div class="studio-row"><label>Character rotation <output>${state.rotation}°</output></label><input data-range="rotation" type="range" min="0" max="6" step="1" value="${state.rotation}"></div><div class="studio-row"><label>Ink opacity <output>${state.opacity}%</output></label><input data-range="opacity" type="range" min="50" max="100" value="${state.opacity}"></div><div class="studio-row"><label>Letter spacing <output>${state.spacing}px</output></label><input data-range="spacing" type="range" min="-1" max="4" step=".5" value="${state.spacing}"></div><div class="studio-row"><label>Line height <output>${state.lineHeight}px</output></label><input data-range="lineHeight" type="range" min="24" max="48" value="${state.lineHeight}"></div><div class="studio-actions"><button id="studio-new">New Draft</button><button id="studio-save" class="primary">Save Project</button></div>`;document.body.appendChild(panel);panel.querySelector('.studio-close').onclick=()=>panel.remove();panel.querySelectorAll('[data-paper]').forEach(b=>b.onclick=()=>{state.paper=b.dataset.paper;apply();render()});panel.querySelectorAll('[data-pen]').forEach(b=>b.onclick=()=>{state.pen=b.dataset.pen;apply();render()});panel.querySelectorAll('[data-range]').forEach(i=>i.oninput=()=>{state[i.dataset.range]=Number(i.value);apply();i.previousElementSibling.querySelector('output').textContent=i.value+(i.dataset.range==='rotation'?'°':i.dataset.range==='opacity'?'%':i.dataset.range==='spacing'?'px':i.dataset.range==='lineHeight'?'px':'');});panel.querySelector('#studio-new').onclick=()=>{const c=document.querySelector('.paper-content');if(c)c.innerHTML='';toast('New draft created')};panel.querySelector('#studio-save').onclick=()=>{const c=document.querySelector('.paper-content');const projects=JSON.parse(localStorage.getItem(PROJECTS)||'[]');projects.unshift({id:Date.now(),text:c?.innerHTML||'',settings:Object.assign({},state),createdAt:new Date().toISOString()});localStorage.setItem(PROJECTS,JSON.stringify(projects.slice(0,20)));toast('Project saved locally')};};
  const boot=()=>{inject();const b=document.createElement('button');b.className='studio-install';b.textContent='✦ Studio';b.onclick=()=>render();document.body.appendChild(b);apply(); if(location.search.includes('action=create'))setTimeout(()=>render(),400)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
